### ISSUE TITLE
Why not merge with bluez ?

### ISSUE THREAD

**Issue by jedrus2000** [thxomas/bdaddr#2]
@thxomas First, thanks for your effort ! I am guessing why your changes are not in official bluez branch ?

I have such case, that on one machine, I've Linux for serious work, and Windows to play. 
Now to have both systems paired with Bluetooth headphones (Bose Q35 II), and easy switching between is not possible.
Every time while switching systems, I had to manually delete other system pairing, using headphones app. Then delete pairing in system, and pair again.

As having Intel based Bluetooth chipset, your changes are only option to reduce pain with it: I am changing MAC address.
So i.e. on Windows system Bluetooth card has fake MAC.

**Comment by thxomas** [comment]
Hello,
Nice hack !

As for the reason I did not merge it to bluez is I'm not a big developer and did not have time to figure out howto.

Feel free to do it!

@thxomas
